version: 2
updates:
  - package-ecosystem: npm
    open-pull-requests-limit: 0
    directory: /
    schedule:
      interval: monthly
      day: wednesday
      time: '11:00'
    pull-request-branch-name:
      separator: '-'
  - package-ecosystem: github-actions
    open-pull-requests-limit: 0
    directory: /
    schedule:
      interval: monthly
      day: wednesday
      time: '11:00'
    groups:
      github-actions:
        patterns:
          - '*'
