name: share-preview-url
on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get dest dir
        id: get_dest_dir
        run: echo "DEST_DIR=inline/preview-$GITHUB_HEAD_REF" >> "$GITHUB_OUTPUT"
      - name: share preview url as PR comment
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "This branch has been deployed to s3 / cloudfront.\n\n✅ Preview URL: https://cdn.smileidentity.com/${{ steps.get_dest_dir.outputs.DEST_DIR }}/js/script.js"

