name: test
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set node version
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run pretest
      - name: run tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: "http://localhost:8000"
