name: deploy staging
on:
  push:
    branches: [main]
jobs:
  test:
    uses: ./.github/workflows/test.yml
  smart-camera-web:
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./packages/smart-camera-web
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: deploy to staging to s3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: >-
            --follow-symlinks --delete --exclude '*' --include
            'smart-camera-web.js'
        env:
          AWS_S3_BUCKET: "${{ secrets.AWS_S3_BUCKET }}"
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "${{ secrets.AWS_REGION }}"
          SOURCE_DIR: "./packages/smart-camera-web"
          DEST_DIR: "js/staging"
  embed:
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./packages/embed
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set node version
        uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
      - name: build site
        run: npm run build && npm run build:dist
      - name: deploy to s3 / cloudfront
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "./packages/embed/dist"
          DEST_DIR: "inline/staging"
