name: test
on:
  workflow_call:
jobs:
  smart-camera-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/smart-camera-web
    steps:
      - name: checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: set node version
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      - name: install dependencies
        run: npm ci
      - name: build application
        run: npm run build
      - name: run tests
        uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v6
        with:
          install: false
          start: npm start
          working-directory: ./packages/smart-camera-web
          wait-on: 'http://localhost:8000'
  embed:
    needs: [web-components]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/embed
    steps:
      - name: checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: set node version
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      - name: build web-components dependency
        run: |
          cd ../web-components
          npm ci
          npm run build
      - name: install dependencies
        run: npm ci
      - name: run tests
        uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v6
        with:
          install: false
          start: npm start
          working-directory: ./packages/embed
          wait-on: 'http://localhost:8000'
      - name: upload test failure artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
  web-components:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/web-components
    steps:
      - name: checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: set node version
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      - name: install dependencies
        run: npm ci
      - name: build application
        run: npm run build
      - name: run tests
        uses: cypress-io/github-action@fa4a118725a8f001170d49631ea89e5d66fee626 # v6
        with:
          install: false
          start: npm run dev
          working-directory: ./packages/web-components
          wait-on: 'http://localhost:3005'
      - name: upload test failure artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
